ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [ com.er.legbon.ApplicationKt.module ]
  }

  jwt {
    secret = ${JWT_SECRET}
    issuer = "com.er.legbon"
    audience = "com.er.legbon"
  }
}


